import { ReactNode } from "react";

import { Inter } from "next/font/google";

import "./global.css";

export const metadata = {
  title: "Pokédex",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans bg-background text-white sm:min-w-[40%] md:min-w-[80%] max-w-md mx-auto`}
      >
        <div className="mx-4 md:mx-auto max-w-7xl">{children}</div>
      </body>
    </html>
  );
}
